### ISSUE TITLE
Bug: Unable to display images

### ISSUE THREAD

**Issue by SprintKeyz** [unwieldycat/robodash#44]
**Bug description**
In the latest update of robodash, I am unable to display images. I made a help post in the VTOW #help channel, which I'll insert here:

> I was playing around with robodash in a fresh project and for some reason cannot get it to display an image (any attempt just gives me a blank screen). Here's my relevant main.cpp:

```cpp
#include "main.h"
#include "robodash/api.h"

void test_auto() {
    std::cout << "Test auto" << std::endl;
}

rd::Selector selector({
   {"Test Auto", &test_auto},
});

rd::Console console;

void initialize() {
    rd::Image img("/usd/pros.c");
    img.focus();
}
```

> My SD Card is a 16GB MicroSD which is successfully recognized by the brain. In fact, I can tell it sees my image because this code:

```cpp
void initialize() {
    // using c file apis, check if /usd/pros.c exists
    FILE* file = fopen("/usd/pros.c", "r");
    if (file) {
        std::cout << "File exists" << std::endl;
        fclose(file);
    }
}
```

> Gives me a "file exists".
>
> My image settings for the conversion are as follows:
> 
> Input image is attached to this post
> Image converter color format: CF_INDEXED_8_BIT
> Image converter output format: C array
> Dithering and big endian disabled
> 
> Additionally, the pros.c file is the only file on my SD.

**Expected behavior**
Image is displayed correctly

**Steps to reproduce**
All steps shown above in description. For context, my  source image is here:
![pros](https://github.com/user-attachments/assets/d070a7f4-e612-4117-8b19-700af9393a68)

**Comment by unwieldycat** [comment]
The output format of your converted image should be "Binary RGB888" instead of "C array" when using an SD card. 

Let me know if this works. 🙂

**Comment by SprintKeyz** [comment]
Thanks so much for the reply! Yep, that seems to have fixed it... can't believe I didn't try a different output format :facepalm:. I'll make sure to update the help post I made as well to hopefully aid anyone else who makes the same mistake.
